name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST http://${{ secrets.JENKINS_URL }}/job/tomcat-deploy-pipeline/build \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}
